### PR TITLE
Documented git submodules for building

### PR DESCRIPTION
**Pull request by phklive**
In this PR I propose the addition of documentation to the README.md file of this repo. Documenting the need to use git submodules to be able to build Miden crypto because of the dependency on https://github.com/PQClean/PQClean

### CODE REVIEW

**Review by hackaugusto — APPROVED** [review]
LGTM

**Comment by bobbinth** [comment]
One note: in the current `next` we actually don't use submodules any more. Thought, they may come back after #293.

**Comment by phklive** [comment]
> One note: in the current `next` we actually don't use submodules any more. Thought, they may come back after #293.

Should we close this PR then or should we merge it in case it's needed in the future?

**Comment by bobbinth** [comment]
I'd keep it open but wouldn't merge yet. After we figure how #293 is going to work, we'll either merge or close this.

**Comment by bobbinth** [comment]
Closing this as stale as we probably no longer need the submodules functionality here.

**Pull request closed without merging**
