### PR TITLE
feat: re-export winter-crypto Hasher, Digest & ElementHasher

### LINKED ISSUE #72: Export winter-crypto base traits
We need to export the winter-crypto traits in order to access the available functionality downstream.

`0.1.2` introduced en encapsulation of `winter-crypto` via this library, so the imports are now extracted from here to miden.

Alternatively, we can export the entire winter-crypto library as re-export, but the ideal approach would be to cherry pick the types as we will have more control over what is used downstream.

### PR DESCRIPTION
**Pull request by vlopes11**
closes #72

This commit introduces the re-export of the listed primitives.

They will be used inside Miden to report the security level of the picked primitive, as well as other functionality.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

Could you rebase from latest `main` or `next` - some files here seem to be outdated as compared to `main` (thought, doesn't seem like it is causing conflicts).

**Comment by vlopes11** [comment]
@bobbinth done! Should we target `main` or `next` for this next `0.1.5`?

**Comment by bobbinth** [comment]
> Should we target `main` or `next` for this next `0.1.5`?

Not sure - we can probably merge this directly into `main` and leave `next` for `0.2` release. But then we need to make sure that `next` is in sync with `main.`

**Comment by vlopes11** [comment]
@bobbinth Then I think its best to follow the normal workflow, that is: merge this into `next`, and then create a PR from `next` into `main`

**Pull request merged**
