### PR TITLE
refactor: Mmr accumulator

### PR DESCRIPTION
**Pull request by frisitano**
## Describe your changes
This PR refactors the `MmrPeaks` interface to decouple padding and hashing peaks.  We publicly expose the method for padding peak such that downstream consumers can leverage it. 

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Overall, this looks fine and I think we can merge - but something doesn't feel quite right to me.

This is not about this PR specifically, but more about tying logic here to Miden VM. Ideally, components here shouldn't be aware of Miden VM - but I'm not sure what's the best way to go about it yet.

**Comment by frisitano** [comment]
> Overall, this looks fine and I think we can merge - but something doesn't feel quite right to me.
> 
> This is not about this PR specifically, but more about tying logic here to Miden VM. Ideally, components here shouldn't be aware of Miden VM - but I'm not sure what's the best way to go about it yet.

Good point, I agree. One proposal would be to remove the vm specific logic from here.  Then use the [wrapped `ChainMmr` struct](https://github.com/0xPolygonMiden/miden-base/pull/110/files#diff-5aa9c48e7599659b65ecfe9512d50934f7beb061c4ab627f87101c34e5702f90R1-R49) to implement the vm specific logic - we could rename `ChainMmr` to be more generic if desired.

**Comment by bobbinth** [comment]
One issue is that the code in `stdlib` does assume this padding for MMR - so, putting the padding logic in `miden-base` doesn't solve it (I think).

**Comment by frisitano** [comment]
> One issue is that the code in `stdlib` does assume this padding for MMR - so, putting the padding logic in `miden-base` doesn't solve it (I think).

good point.  I'll merge this for now and we can spend some time to think of a cleaner solution

**Pull request merged**
