### PR TITLE
[WIP] RPO hash function SVE implementation

### PR DESCRIPTION
**Pull request by jrchatruc**
This PR addresses #158. It uses C `SVE` instrinsics to reimplement the `apply_inv_sbox` section of RPO, by far the most expensive part of it. There is also a regular `C` implementation written for testing purposes.

An `sve_backend` feature flag is introduced, which swaps the `apply_inv_sbox` function to the `SVE` version when toggled. This will only compile on machines with the `SVE` instruction set. To compare the two implementations, run

```
cargo bench hash
```

for the benchmarks of the current implementation and

```
cargo bench hash --features sve_backend
```

for the SVE one. 

Currently the `SVE` implementation is around 3X slower, but this is most likely because of inefficiencies in the implementation, which is constantly passing data between SVE and non SVE code. We will improve it in the following days.

TODO:

- [ ] Improve performance
- [ ] Document code

### CODE REVIEW

**Comment by tohrnii** [comment]
Tried implementing this as well and getting similar results as you at 3x slower.

> but this is most likely because of inefficiencies in the implementation, which is constantly passing data between SVE and non SVE code

This seems like the likely culprit to me as well.

One thing, I didn't see any improvement with loop unrolling for `exp_acc` so maybe those functions can be combined and `m` can be passed as an argument instead. Here's my current code if it helps but I imagine it should be similar to yours.

```
#ifndef __ARM_FEATURE_SVE
#warning "We need SVE!"
#endif
#include "sve-functions.h"
#include <stdio.h>

svuint64_t mont_red_cst(svbool_t pg, svuint64_t xl, svuint64_t xh) {
    svuint64_t a0 = svlsl_n_u64_z(pg, xl, 32);
    svuint64_t a = svadd_u64_z(pg, xl, a0);
    svbool_t overflow_xl = svcmpgt_u64(pg, xl, a);
    svuint64_t e = svsel(overflow_xl, svdup_n_u64(1), svdup_n_u64(0));
    
    svuint64_t b = svsub_u64_z(pg, svsub_u64_z(pg, a, svlsr_n_u64_z(pg, a, 32)), e);

    svuint64_t r = svsub_u64_z(pg, xh, b);
    
    svbool_t overflow1 = svcmpgt_u64(pg, r, xh);
    svuint32_t c = svsel(overflow1, svdup_n_u32(1), svdup_n_u32(0));
    svuint32_t neg_c = svsub_u32_z(pg, svdup_n_u32(0), c);
    svuint64_t neg_c_u64 = svreinterpret_u64_u32(neg_c);
    return svsub_u64_z(pg, r, neg_c_u64);
}

svuint64_t mul(svbool_t pg, svuint64_t x, svuint64_t y) {
    svuint64_t xyl = svmul_u64_z(pg, x, y);
    svuint64_t xyh = svmulh_u64_z(pg, x, y);

    return mont_red_cst(pg, xyl, xyh);
}

svuint64_t square_sve(svbool_t pg, svuint64_t x) {
    svuint64_t y = x;
    svuint64_t r1 = svdup_n_u64(0xFFFFFFFE00000001);
    svuint64_t xl = svmul_u64_z(pg, x, r1);
    svuint64_t xh = svmulh_u64_z(pg, x, r1);
    svuint64_t x_mont = mont_red_cst(pg, xl, xh);
    svuint64_t yl = svmul_u64_z(pg, y, r1);
    svuint64_t yh = svmulh_u64_z(pg, y, r1);
    svuint64_t y_mont = mont_red_cst(pg, yl, yh);
    return mul(pg, x_mont, y_mont);
}

svuint64_t exp_acc(svbool_t pg, svuint64_t x, svuint64_t y, uint8_t m) {
    svuint64_t resultx = x;
    for (uint8_t i = 0; i < m; i++) {
        resultx = square_sve(pg, resultx);
    }
    return mul(pg, resultx, y);
}

void apply_inv_sbox(uint64_t *data) {
    svbool_t pg = svptrue_b64();

    svuint64_t result0;
    svuint64_t result1;
    svuint64_t result2;
    svuint64_t sve_data0 = svld1_u64(pg, &data[0]);
    svuint64_t sve_data1 = svld1_u64(pg, &data[4]);
    svuint64_t sve_data2 = svld1_u64(pg, &data[8]);
    svuint64_t t10 = square_sve(pg, sve_data0);
    svuint64_t t11 = square_sve(pg, sve_data1);
    svuint64_t t12 = square_sve(pg, sve_data2);
    svuint64_t t20 = square_sve(pg, t10);
    svuint64_t t21 = square_sve(pg, t11);
    svuint64_t t22 = square_sve(pg, t12);
    svuint64_t t30 = exp_acc(pg, t20, t20, 3);
    svuint64_t t31 = exp_acc(pg, t21, t21, 3);
    svuint64_t t32 = exp_acc(pg, t22, t22, 3);
    svuint64_t t40 = exp_acc(pg, t30, t30, 6);
    svuint64_t t41 = exp_acc(pg, t31, t31, 6);
    svuint64_t t42 = exp_acc(pg, t32, t32, 6);
    svuint64_t t50 = exp_acc(pg, t40, t40, 12);
    svuint64_t t51 = exp_acc(pg, t41, t41, 12);
    svuint64_t t52 = exp_acc(pg, t42, t42, 12);
    svuint64_t t60 = exp_acc(pg, t50, t30, 6);
    svuint64_t t61 = exp_acc(pg, t51, t31, 6);
    svuint64_t t62 = exp_acc(pg, t52, t32, 6);
    svuint64_t t70 = exp_acc(pg, t60, t60, 31);
    svuint64_t t71 = exp_acc(pg, t61, t61, 31);
    svuint64_t t72 = exp_acc(pg, t62, t62, 31);
    svuint64_t a0 = square_sve(pg, square_sve(pg, mul(pg, square_sve(pg, t70), t60)));
    svuint64_t a1 = square_sve(pg, square_sve(pg, mul(pg, square_sve(pg, t71), t61)));
    svuint64_t a2 = square_sve(pg, square_sve(pg, mul(pg, square_sve(pg, t72), t62)));
    svuint64_t b0 = mul(pg, mul(pg, t10, t20), sve_data0);
    svuint64_t b1 = mul(pg, mul(pg, t11, t21), sve_data1);
    svuint64_t b2 = mul(pg, mul(pg, t12, t22), sve_data2);
    result0 = mul(pg, a0, b0);
    result1 = mul(pg, a1, b1);
    result2 = mul(pg, a2, b2);
    svst1(pg, &data[0], result0);
    svst1(pg, &data[4], result1);
    svst1(pg, &data[8], result2);
}

int main() {
    uint64_t data[12] = {84921628, 984652231, 84515038, 462616238, 465213287, 456213874, 234162137, 89462132, 98546216, 1054621313, 164162331, 18546232};
    apply_inv_sbox(data);
    return 0;
}
```

**Comment by tohrnii** [comment]
One other thing to investigate is how much FFI overhead there is. With some rudimentary analysis it seemed like a lot to me but it's possible that I made a mistake and that's not actually the case.

**Comment by jrchatruc** [comment]
@tohrnii Thanks for the comment! Our code looks quite similar but not exactly the same so it'll be useful to compare.

> One other thing to investigate is how much FFI overhead there is. With some rudimentary analysis it seemed like a lot to me but it's possible that I made a mistake and that's not actually the case.

This is interesting, how are you measuring the overhead?

**Comment by tohrnii** [comment]
@jrchatruc Actually, I realize that is probably not accurate since I used `gettimeofday()` to measure time which is much lower precision than what we need (I don't know C that much so probably made a few other obvious mistakes). One data point that might still be relevant is that using `cargo bench` for RPO 2-to-1 hash, the time increased by 10% when I replaced just one multiplication with SVE implementation (however this could also be because of overhead of converting the values from `Felt` to `u64` and converting back and loading and unloading array into SVE registers). Some other data points to establish some baseline:
On a 1 core AWS graviton machine, cargo bench for RPO 2-to-1 hash:
1. Time taken for native implementation: 11 us
2. Time taken with SVE without inlining functions: 48 us
3. Time taken with SVE with inlining: 33 us

**Comment by bobbinth** [comment]
Superseded by #190.

**Pull request closed without merging**
